version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - tp_network
    container_name: text_piece_elasticsearch

  app:
    build: .
    ports:
      - 80:80
    depends_on:
      - elasticsearch
    networks:
      - tp_network
    container_name: text_piece_app

networks:
  tp_network:
    driver: bridge